export enum OIDCEvents {
  AUTHENTICATION_REQUIRED,
  AUTHENTICATION_DATA_RECEIVED,
  AUTHENTICATED,
  USER_INFO_REQUIRED,
  USER_INFO_RECEIVED,
  SESSION_END_REQUIRED,
  SESSION_ENDED,
  AUTHENTICATION_FAILED,
}
